### ISSUE TITLE
mysql  或者MariaDB 镜像无法修改 mysql 配置

### ISSUE THREAD

**Issue by charlesyq** [bravist/lnmp-docker#10]
![image](https://user-images.githubusercontent.com/10511724/34034679-643a746c-e1ba-11e7-9f7d-e4f942723f40.png)
已经变更了my.conf  修改了sql_mode 但是sql_mode 仍然还是默认的，请问需要如何解决

**Comment by huiyonghkw** [comment]
当前， 不支持你这样的修改方式，具体如何修改mariadb配置，参考：https://hub.docker.com/_/mariadb/

Using a custom MySQL configuration file

**Comment by charlesyq** [comment]
话说我是按照上边来的呀， -v 就是挂载的意思，我这也是挂载呀，然后执行
chcon -Rt svirt_sandbox_file_t /my/custom
提示
![image](https://user-images.githubusercontent.com/10511724/34238403-5031f64e-e63c-11e7-8040-524838016d20.png)
然后在重启mysql 后sql_mode 还是默认值不是我设定的

**Comment by huiyonghkw** [comment]
您说的是想修改my.conf中的这个值吗？

```bash
...
# If applications support it, this stricter sql_mode prevents some
#sql_mode		= NO_ENGINE_SUBSTITUTION,TRADITIONAL


```

真要修改的话，请先fork此仓库，然后在mariadb/下增加dockerfile，将您的my.conf添加进dockerfile。

**Comment by khs1994** [comment]
把你的配置文件贴上来，我们帮你调一下

**Comment by charlesyq** [comment]
万分感谢，主要是添加以下的配置

[mysqld]
bind-address=0.0.0.0
sql_mode=NO_ENGINE_SUBSTITUTION

**Comment by khs1994** [comment]
在 `./mariadb/config.d` 目录执行 `ls -la` 截图过来，我怀疑你配置文件后缀名错了，不是`*.conf` 而是 `*.cnf`
