### ISSUE TITLE
报错信息

### ISSUE THREAD

**Issue by luo964973791** [bravist/lnmp-docker#11]
一直报错
cc92f71d0ae9        lnmpdocker_call-websocket             "/usr/bin/php /usr..."   6 seconds ago       Exited (1) 4 seconds ago                            lnmp-call-websocket
dd5326f14d84        lnmpdocker_laravel-qrcode-websocket   "/usr/bin/php /usr..."   6 seconds ago       Exited (1) 4 seconds ago                            lnmp-laravel-qrcode-we
8df050580d40        tianon/true                           "/true"                  7 seconds ago       Exited (0) 5 seconds ago                            lnmp-www
![k9sg77 1a154 bu1g6 8 o](https://user-images.githubusercontent.com/31985163/35601856-1f4c30e0-0670-11e8-98b4-d189ed15c11b.png)

**Comment by huiyonghkw** [comment]
浏览这个文件：laravel-qrcode-websocket/Dockerfile，发现：

```bash
CMD ["/usr/bin/php", "/usr/share/nginx/html/open.weipeiapp.com/artisan", "socket:serve"]
```

也就是需要在www目录下新建open.weipeiapp.com目录。你可以忽略这个错误

因为这套运行提示是基于我们实际的项目运行，所以文档还不太完善，我会再次优化文档

**Comment by luo964973791** [comment]
但是没有看到lnmpdocker_nginx这个nginx容器
![iq96eh w 328r py i8 goi](https://user-images.githubusercontent.com/31985163/35602111-74666c84-0671-11e8-91cc-80d3c3f0550e.png)

**Comment by huiyonghkw** [comment]
使用
```bash
docker ps -a 
```
查看所有的容器信息，包括未启动的容器，然后在使用

```bash
docker logs lnmp-docker_nginx 
```

查看错误信息

**Comment by brelian** [comment]
我也遇到同样的错误

**Comment by AuroraLZDF** [comment]
`Step 2/7 : COPY ./crontabs/default /var/spool/cron/crontabs/
ERROR: Service 'php-crond' failed to build: COPY failed: stat /var/lib/docker/tmp/docker-builder327772964/crontabs/default: no such file or directory`

**Comment by huiyonghkw** [comment]
@AuroraLZDF ，请关注https://github.com/bravist/lnmp-docker#%E5%AE%89%E8%A3%85lnmp-docker 第三点描述
