### ISSUE TITLE
php-supervisor 配置好后，可以正常启动。但是没有执行命令

### ISSUE THREAD

**Issue by xskjs888** [bravist/lnmp-docker#12]
请问 php-supervisor 的正确使用姿势是什么呀。 环境都起来了。就是，不执行配置好的脚本。

[program:examine]
command=/usr/share/nginx/html/default/data/bin/examine
autostart=true

这样配置有问题吗？   log文件夹下什么也没有。 怎么看有没有启动啊？

**Comment by huiyonghkw** [comment]
![image](https://user-images.githubusercontent.com/1323776/37262035-9850a3ec-25db-11e8-8cb4-07157fe0573c.png)

第一，使用docker ps 或者 docker ps -a 查看是否启动了lnmp-php-supervisor。

第二，使用 docker logs  lnmp-php-supervisor 查看是否存在报错信息

第三，提供一份这样的参考：

```bash

[program:yj.weipeiapp.com_excel_parse]
command                 = /usr/bin/php /usr/share/nginx/html/yj.com/artisan queue:work redis --queue=excel_parse  --sleep=3 --tries=1  --daemon
process_name            = %(program_name)s_%(process_num)02d
numprocs                = 1
autostart               = true
autorestart             = true
stdout_logfile          = /tmp/supervisor_queue_yj_com_excel_parse.log
stdout_logfile_maxbytes = 10MB
stderr_logfile          = /tmp/supervisor_queue_yj_com_excel_parse.err.log
stderr_logfile_maxbytes = 10MB

```
