### ISSUE TITLE
db 容器出错

### ISSUE THREAD

**Issue by toshcn** [bravist/lnmp-docker#13]
$ sudo docker-compose up -d
WARNING: The PHP_FPM_DOMAIN6 variable is not set. Defaulting to a blank string.
WARNING: The SUPERVISOR_DOMAIN6 variable is not set. Defaulting to a blank string.
Creating network "lnmp-docker_web_server_network" with driver "bridge"
Creating network "lnmp-docker_default" with the default driver
Creating lnmp-www ... 
Creating lnmp-redis ... 
Creating lnmp-mariadb ... error
Creating lnmp-www     ... done
Creating lnmp-redis          ... done
f9bcd8e1e53838313f0130): Error starting userland proxy: listen tcp 0.0.0.0:3306: bind: address already in use
Creating lnmp-php-crond      ... done
Creating lnmp-call-websocket ... done

ERROR: for mariadb  Cannot start service mariadb: driver failed programming external connectivity on endpoint lnmp-mariadb (3ad9d16efe7c092880635979d06a038f96bdef7931f9bcd8e1e53838313f0130): Error starting userland proxy: listen tcp 0.0.0.0:3306: bind: address already in use
ERROR: Encountered errors while bringing up the project.

**Comment by toshcn** [comment]
知道了，宿主3306端口已经被用了 ^~^

**Comment by huiyonghkw** [comment]
感谢使用
