### ISSUE TITLE
启动不了

### ISSUE THREAD

**Issue by toshcn** [bravist/lnmp-docker#14]
$ sudo docker-compose up -d
WARNING: The PHP_FPM_DOMAIN6 variable is not set. Defaulting to a blank string.
WARNING: The SUPERVISOR_DOMAIN6 variable is not set. Defaulting to a blank string.
Creating network "lnmp-docker_web_server_network" with driver "bridge"
Creating network "lnmp-docker_default" with the default driver
Creating lnmp-redis   ... done
Creating lnmp-mariadb        ... done
Creating lnmp-www     ... done
Creating lnmp-php-crond ... 
Creating lnmp-call-websocket ... 
Creating lnmp-php-fpm        ... error
Creating lnmp-php-supervisor ... 
Creating lnmp-php-crond      ... done
Creating lnmp-call-websocket ... done

ERROR: for lnmp-php-supervisor  Cannot create container for service php-supervisor: bad format for add-host: ":172.16.41.20"

ERROR: for php-fpm  Cannot create container for service php-fpm: bad format for add-host: ":172.16.41.20"

ERROR: for php-supervisor  Cannot create container for service php-supervisor: bad format for add-host: ":172.16.41.20"
ERROR: Encountered errors while bringing up the project.

**Comment by toshcn** [comment]
我靠，原来.env 里少了两个参数PHP_FPM_DOMAIN6，SUPERVISOR_DOMAIN6 补上就好了

**Comment by huiyonghkw** [comment]
感谢使用
