### ISSUE TITLE
作者还在吗?

### ISSUE THREAD

**Issue by kasenhoo** [bravist/lnmp-docker#19]
ERROR: error pulling image configuration: Get https://muehonsf.mirror.aliyuncs.com/v2/bravist/php-fpm-alpine-aliyun-app/blobs/sha256:177296a7c36fded2f87bb65afab6ad1c036b32a19687586621a62324984b2477: dial tcp 116.62.81.173:443: i/o timeout

**Comment by huiyonghkw** [comment]
晚些时候处理， 感谢反馈

**Comment by huiyonghkw** [comment]
> ERROR: error pulling image configuration: Get https://muehonsf.mirror.aliyuncs.com/v2/bravist/php-fpm-alpine-aliyun-app/blobs/sha256:177296a7c36fded2f87bb65afab6ad1c036b32a19687586621a62324984b2477: dial tcp 116.62.81.173:443: i/o timeout

感谢反馈，已经完全修复。主要是因为阿里云镜像站HTTP迁移到了HTTPS。
