### ISSUE TITLE
当我想使用exec命令进行容器内部时，得到如下错误

### ISSUE THREAD

**Issue by walijoy** [bravist/lnmp-docker#4]
$ sudo docker exec -it lnmp-nginx bash
`rpc error: code = 2 desc = oci runtime error: exec failed: container_linux.go:247: starting container process caused "exec: \"bash\": executable file not found in $PATH"
`

**Comment by walijoy** [comment]
该容器正确命令是 docker exec -it lnmp-nginx sh

**Comment by huiyonghkw** [comment]
@hookover -_-
