### ISSUE TITLE
能否为镜像加个phpredis扩展？

### ISSUE THREAD

**Issue by walijoy** [bravist/lnmp-docker#6]
我不知道怎么加……

**Comment by huiyonghkw** [comment]
![image](https://user-images.githubusercontent.com/1323776/31860179-105ac076-b6dc-11e7-834e-28ae41b01ae5.png)


![image](https://user-images.githubusercontent.com/1323776/31860209-572689b8-b6dc-11e7-999f-d69e8414573a.png)

@baoniu 容器已经支持redis。你是遇到了其他什么问题呢？
