### ISSUE TITLE
镜像加速，建议采用 https://registry.docker-cn.com

### ISSUE THREAD

**Issue by khs1994** [bravist/lnmp-docker#8]

**Comment by huiyonghkw** [comment]
>... 该镜像库只包含流行的公有镜像。私有镜像仍需要从美国镜像库中拉取。...

私有仓库还得从国外去获取，可能还是建议使用淘宝镜像

**Comment by khs1994** [comment]
实际用一下吧，我自己实际用着速度还行。用阿里镜像，还得登录账号，查看，以后新配置还得登录到网站查看地址，要么用个 “小本本” 记录地址，哈哈。

**Comment by huiyonghkw** [comment]
嗯嗯， 可以考虑，感谢反馈
